#!/bin/sh

# Check if params are enough to go ahead.
sourceBranch=$1
switch=$2
test -z "$sourceBranch" && echo "ERROR: Please provide the source remote branch." 1>&2 && exit 1
test -n "$switch" && test "$switch" != "--prune" && echo "Switch invalid! Allowed switch(es) are --prune" 1>&2 && exit 1

# Find which is your current branch
if currentBranch=$(git symbolic-ref --short -q HEAD)
then
    echo On branch "$currentBranch"
    echo "Pulling updates from the remote branch $sourceBranch ..."
    # Stash current changes
    git stash
    # Checkout remote branch from where you want to update. 
    git checkout "$sourceBranch"
    git fetch
    git pull
    # Delete all branches that are merged into source branch
    git branch --merged $sourceBranch | grep -v "(^\*|master|$sourceBranch)" | xargs -n 1 git branch -d

    echo "Removed all merged branches based on $sourceBranch"

    if [ "$switch" == "--prune" ]
    then
        git fetch "$switch"
        git branch -r --merged | grep -v "(^\*|master|$sourceBranch)" | sed -e 's/origin\//:/' | xargs -r git push origin
    fi
else
    echo ERROR: Cannot find the current branch!
fi
# 